RipCore/RipCore/Models/Entities/Solution.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RipCore.Models.Entities
{
    public class Solution
    {
        public int ID { get; set; }
        public int MilestoneID { get; set; }
        public string StudentID { get; set; }
        public string Code { get; set; }
        public int SubmissionID { get; set; }
        public decimal Grade { get; set; }
    }
}

RipCore/RipCore/Models/Entities/Submission.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RipCore.Models.Entities
{
    public class Submission
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public int MilestoneID { get; set; }
        public bool IsAccepted { get; set; }
        public string SolutionOutput { get; set; }
        public string ExpectedOutput { get; set; }
        public string Code { get; set; }
    }
}

RipCore/RipCore/Models/ViewModels/SolutionViewModel.cs
using RipCore.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RipCore.Models.ViewModels
{
    public class SolutionViewModel
    {
        public int ID { get; set; }
        public int CurrentBestID { get; set; }
        public int MilestoneID { get; set; }
        public decimal? Grade { get; set; }
        public string StudentID { get; set; }

        public string Code { get; set; }
        //public List<Solution> UserSubmissions;
        //public List<Solution> AllSubmissions;
        //public Submission CurrentBest { get; set; }

        public List<Solution> UserSubmissions;
        public List<Solution> AllSubmissions;

        public Submission CurrentBest { get; set; }

    }
}

RipCore/RipCore/Models/ViewModels/SubmissionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RipCore.Models.ViewModels
{
    public class SubmissionViewModel
    {
        public int ID { get; set; }
        public string UsersName { get; set; }
        public string UsersID { get; set; }
        public string AssignmentName { get; set; }
        public string MilestoneName { get; set; }
        public int MilestoneID { get; set; }
        public bool IsAccepted { get; set; }
        public bool IsTeacher { get; set; }
        public List<string> SolutionOutput;
        public decimal Grade { get; set; }
        public string Code { get; set; }
        public List<string> ExpectedOutput;
        public string ProgrammingLanguage { get; set; }
    }
}

RipCore/RipCore/Controllers/SolutionController.cs
using Microsoft.AspNet.Identity;
using RipCore.Models;
using RipCore.Models.Entities;
using RipCore.Models.ViewModels;
using RipCore.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using static System.Net.Mime.MediaTypeNames;

namespace RipCore.Controllers
{
    /// <summary>
    /// A controller class that controls the actions  regarding solutions.
    /// Especially regarding compiling
    /// </summary>
    public class SolutionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private SolutionService sService = new SolutionService();
        private AssignmentsService aAssignment = new AssignmentsService();

        /// <summary>
        /// Spyrja johonnu þegar hun hefur tima
        /// </summary>
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult SubmitSolution(AssignmentViewModel viewModel)
        {
            SubmissionViewModel submission = new SubmissionViewModel { AssignmentName = viewModel.Title, MilestoneID = viewModel.milestoneSubmissionID  };
            Assignment assigment = (from s in db.Assignments
                                    where s.ID == viewModel.ID
                                    select s).FirstOrDefault();
            submission.ProgrammingLanguage = aAssignment.GetProgrammingLanguageByID(assigment.ProgrammingLanguageID);
            if (viewModel.File != null)
            {
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    viewModel.File.InputStream.CopyTo(memoryStream);

                    string result = Encoding.ASCII.GetString(memoryStream.ToArray());
                    submission.Code = result;
                }
            }
            else if (!string.IsNullOrEmpty(viewModel.Solution))
            {
                submission.Code = viewModel.Solution;
            }

            if (submission.ProgrammingLanguage == "regex")
            {
                return RedirectToAction("RegexTest", submission);
            }

            if (submission.ProgrammingLanguage == "other")
            {
                return RedirectToAction("Other", submission);
            }

            if (submission.ProgrammingLanguage == "otherNotTests")
            {
                return RedirectToAction("OtherWithTests", submission);
            }
            return RedirectToAction("CompileSolution", submission);
        }
        /// <summary>
        /// A function that compiles a solution, checks for an infinite loop
        /// and checks if it validates for input/output pairs
        /// </summary>
        //[HttpPost] // ??
        [ValidateInput(false)]
        public ActionResult CompileSolution(SubmissionViewModel data)
        {
            var code = data.Code;
            data.ExpectedOutput = new List<string>();
            data.SolutionOutput = new List<string>();
            string user = User.Identity.GetUserId();

            string smu = AppDomain.CurrentDomain.BaseDirectory;

            var workingFolder = smu + user + "\\"; //name; // eða ID
            System.IO.Directory.CreateDirectory(workingFolder);

            var cppFileName = data.AssignmentName.Replace(" ", "").ToLower() + data.ProgrammingLanguage; // ---- Verkefnaheiti
            var exeFilePath = workingFolder + data.AssignmentName.Replace(" ", "").ToLower() + ".exe"; // ----- verkefnaheiti

            // Write the code to a file, such that the compiler
            // can find it:
            System.IO.File.WriteAllText(workingFolder + cppFileName, code);

            // In this case, we use the C++ compiler (cl.exe) which ships
            // with Visual Studio. It is located in this folder:
            string compilerFolder;
            if (data.ProgrammingLanguage == ".cs")
            {
                compilerFolder = "C:\\Windows\\Microsoft.NET\\Framework\\v3.5\\";
            }
            else
            {
                compilerFolder = "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\";
            }
            // There is a bit more to executing the compiler than
            // just calling cl.exe. In order for it to be able to know
            // where to find #include-d files (such as <iostream>),
            // we need to add certain folders to the PATH.
            // There is a .bat file which does that, and it is
            // located in the same folder as cl.exe, so we need to execute
            // that .bat file first.

            // Using this approach means that:
            // * the computer running our web application must have
            //   Visual Studio installed. This is an assumption we can
            //   make in this project.
            // * Hardcoding the path to the compiler is not an optimal
            //   solution. A better approach is to store the path in
            //   web.config, and access that value using ConfigurationManager.AppSettings.

            // Execute the compiler:
            Process compiler = new Process();
            if (data.ProgrammingLanguage == ".cs")
            {
                compiler.StartInfo.FileName = "cmd.exe";
                compiler.StartInfo.WorkingDirectory = workingFolder;
                compiler.StartInfo.RedirectStandardInput = true;
                compiler.StartInfo.RedirectStandardError = true;
                compiler.StartInfo.RedirectStandardOutput = true;
                compiler.StartInfo.UseShellExecute = false;

                compiler.Start();
                compiler.StandardInput.WriteLine("C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\CSC.EXE " + cppFileName);
                compiler.StandardInput.WriteLine("exit");
                Debug.WriteLine(compiler.StandardError.ReadLine());
            }
            
            else
            {                
                compiler.StartInfo.FileName = "cmd.exe";
                compiler.StartInfo.WorkingDirectory = workingFolder;
                compiler.StartInfo.RedirectStandardInput = true;
                compiler.StartInfo.RedirectStandardOutput = true;
                compiler.StartInfo.UseShellExecute = false;

                compiler.Start();
                compiler.StandardInput.WriteLine("\"" + compilerFolder + "vcvars32.bat" + "\"");
                compiler.StandardInput.WriteLine("cl.exe /nologo /EHsc " + cppFileName);
                compiler.StandardInput.WriteLine("exit");
                string output = compiler.StandardOutput.ReadToEnd();
            }
          //  var compilerTest = compiler.WaitForExit(10000);
            //if (!compilerTest)
            //{
                //data.SolutionOutput.Add("Compile Time Error!");
                //compiler.Kill();
                //return View(data);
            //}
            compiler.Close();


            // Check if the compile succeeded, and if it did,
            // we try to execute the code:
            if (System.IO.File.Exists(exeFilePath))
            {
                var processInfoExe = new ProcessStartInfo(exeFilePath, "");
                processInfoExe.UseShellExecute = false;
                processInfoExe.RedirectStandardOutput = true;
                processInfoExe.RedirectStandardInput = true;
                processInfoExe.RedirectStandardError = true;
                processInfoExe.CreateNoWindow = true;
                string entityOutput = "";
                string entityExpected = "";
                List <Tuple<string, string>> excpectedData = sService.GetExpectedData(data.MilestoneID);
                for (int i = 0; i < excpectedData.Count; i++)
                {
                    using (var processExe = new Process())
                    {
                        processExe.StartInfo = processInfoExe;
                        processExe.Start();

                        if (excpectedData[i].Item1 != "")
                        {
                            processExe.StandardInput.WriteLine(excpectedData[i].Item1);
                        }

                        var RunTimeTest = processExe.WaitForExit(5000);
                        if (!RunTimeTest)
                        {
                            data.SolutionOutput.Add("Run Time Error!");
                            entityOutput += "Run Time Error";
                            processExe.Kill();
                            return View(data);
                        }

                        string programOutput = "";
                        while (!processExe.StandardOutput.EndOfStream)
                        {
                            programOutput = processExe.StandardOutput.ReadLine();
                        }

                        ViewBag.Output = programOutput;
                        if (!String.IsNullOrEmpty(programOutput))
                        {
                            data.SolutionOutput.Add(programOutput);
                            entityOutput += programOutput + ' ';
                        }
                        data.ExpectedOutput.Add(excpectedData[i].Item2);
                        entityOutput += excpectedData[i].Item2 + ' ';
                        if (string.Equals(programOutput, excpectedData[i].Item2))
                        {
                            data.IsAccepted = true;
                        }
                        else
                        {
                            data.IsAccepted = false;
                            break;
                        }
                    }
                }

                Submission submission = new Submission { MilestoneID = data.MilestoneID, IsAccepted = data.IsAccepted, SolutionOutput = entityOutput, UserID = User.Identity.GetUserId(), Code = data.Code, ExpectedOutput = entityExpected};

RipCore/RipCore/Views/Solution/AllSolutions.cshtml
@model RipCore.Models.ViewModels.SolutionOverViewModel

@{
    ViewBag.Title = @Resources.Resources.allSolutions;
}

@for (int i = 0; i < Model.MilestoneNames.Count(); i++)
{
    <h2>@Model.MilestoneNames[i].Title</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-md-2">
                    @Resources.Resources.User
                </th>
                <th class="col-md-offset-2 col-md-3">
                    @Resources.Resources.Submission
                </th>
                <th class="col-md-offset-2 col-md-3">
                    @Resources.Resources.Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AssignmentSolutions[i])
            {
                <tr>
                    <td class="col-md-2">
                        <h6>
                            @item.StudentID
                        </h6>
                    </td>
                    <td class="col-md-offset-2 col-md-3">
                        <h6>
                            @Html.ActionLink(@Resources.Resources.SeeSubmissions, "SubmissionDetails", new { id = item.CurrentBestID, isTeacher = true })
                        </h6>
                    </td>
                    <td class="col-md-offset-2 col-md-3">
                        @if (item.CurrentBest.IsAccepted)
                        {
                            <h6>
                                Accepted
                            </h6>
                        }
                        else
                        {
                            <h6>
                                Not Accepted
                            </h6>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

@for (int i = 0; i < Model.MilestoneNames.Count; i++)
{
    <h2>@Model.MilestoneNames[i].Title</h2>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-md-2">
                    User
                </th>
                <th class="col-md-offset-2 col-md-3">
                    Submission
                </th>
                <th class="col-md-offset-2 col-md-3">
                    Status
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.AssignmentSolutions[i])
            {
                <tr>
                    <td class="col-md-2">
                        <h6>
                            Anonymous
                        </h6>
                    </td>
                    <td class="col-md-offset-2 col-md-3">
                        <h6>
                            @Html.ActionLink("See submission", "SubmissionDetails", new { id = item.CurrentBestID, isTeacher = true })
                        </h6>
                    </td>
                    <td class="col-md-offset-2 col-md-3">
                        @if (item.CurrentBest.IsAccepted)
                        {
                            <h6>
                                Accepted
                            </h6>
                        }
                        else
                        {
                            <h6>
                                Not Accepted
                            </h6>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

RipCore/RipCore/Views/Solution/AllSubmissions.cshtml
@model RipCore.Models.ViewModels.SubmissionsOverViewModel

@{
    ViewBag.Title = "Edit";
}
<h2>All Submissions</h2>
@{ Html.RenderPartial("Submissions"); }

RipCore/RipCore/Views/Solution/CompileSolution.cshtml
@model RipCore.Models.ViewModels.SubmissionViewModel
@if(Model.IsAccepted)
{
    <h3 class="accepted">Accepted</h3>
}

@if(!Model.IsAccepted)
{
    <h3 class="notAccepted">Not Accepted</h3>

}
<div class="row">
    @if (Model.SolutionOutput.Count != 0)
    {
        <div class="col-md-4">
            <div class="col-md-10">
                @Html.LabelFor(model => model.SolutionOutput, "Your result:", htmlAttributes: new { @class = "control-label col-md-4" })
            </div>
            <div class="col-md-10">
                @foreach (var item in Model.SolutionOutput)
                {
                    <p>@item</p>
                }
            </div>
        </div>
    }
    @if (Model.ExpectedOutput.Count != 0)
    {
        <div class="col-md-4">
            <div class="col-md-10">
                @Html.LabelFor(model => model.ExpectedOutput, "Expected result:", htmlAttributes: new { @class = "control-label col-md-4" })
            </div>
            <div class="col-md-10">
                @foreach (var item in Model.ExpectedOutput)
                {
                    <p>@item</p>
                }
            </div>
        </div>
    }

</div>

RipCore/RipCore/Views/Solution/HtmlCode.cshtml
@model RipCore.Models.ViewModels.SubmissionViewModel

@{
    ViewBag.Title = "HtmlCode";
}

<section>
    <div id="editor">
        @Model.Code
    </div>
</section>
<script type="text/javascript">
    var editor = ace.edit("editor");
    //editor.setTheme("ace/theme/twilight");
   // editor.getSession().setMode("ace/mode/c#");
</script>

RipCore/RipCore/Views/Solution/Other.cshtml
@model RipCore.Models.ViewModels.SubmissionViewModel

@{
    ViewBag.Title = "HtmlCode";
}
@{ Html.RenderPartial("TestResults"); }

RipCore/RipCore/Views/Solution/OtherWithTests.cshtml
@model RipCore.Models.ViewModels.SubmissionViewModel
@{ Html.RenderPartial("TestResults"); }

RipCore/RipCore/Views/Solution/RegexTest.cshtml
@model RipCore.Models.ViewModels.SubmissionViewModel
@if (Model.IsAccepted)
{
    <h3 class="accepted">Accepted</h3>
    <p>Your result: @Model.SolutionOutput</p>
    <p>Expected result: @Model.ExpectedOutput</p>
}

@if (!Model.IsAccepted)
{
    <h3 class="notAccepted">Not Accepted</h3>
    <p>Your result: @Model.SolutionOutput</p>
    <p>Expected result: @Model.ExpectedOutput</p>
}

RipCore/RipCore/Views/Solution/SubmissionDetails.cshtml
@model RipCore.Models.ViewModels.SubmissionViewModel
<h3>@Model.MilestoneName</h3>
<h3>@Model.UsersName</h3>
<p>@Model.IsAccepted</p>
<section>
    <div id="editor">
        @Model.Code
    </div>
</section>
<script type="text/javascript">
    var editor = ace.edit("editor");
    //editor.setTheme("ace/theme/twilight");
   // editor.getSession().setMode("ace/mode/c#");
</script>
<div class="form-horizontal">
    <hr />
    <div class="form-group">
        @Html.LabelFor(model => model.ExpectedOutput, "Expected Output", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.ExpectedOutput)
            @Html.ValidationMessageFor(model => model.ExpectedOutput, "", new { @class = "text-danger" })
        </div>
    </div>
    @if (!Model.IsTeacher)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.SolutionOutput, "Your Output", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.SolutionOutput)
                @Html.ValidationMessageFor(model => model.SolutionOutput, "", new { @class = "text-danger" })
            </div>
        </div>
        if (Model.Grade != 0)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Grade, "Grade", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Grade)
                    @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
                </div>
            </div>
        }
    }
    @if (Model.IsTeacher)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.SolutionOutput, "Obtained Output", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.SolutionOutput)
                @Html.ValidationMessageFor(model => model.SolutionOutput, "", new { @class = "text-danger" })
            </div>
        </div>
        using (Html.BeginForm("SubmitGrade", "Solution", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.IsAccepted)
            @Html.HiddenFor(model => model.MilestoneID)
            @Html.HiddenFor(model => model.SolutionOutput)
            @Html.HiddenFor(model => model.ExpectedOutput)
            @Html.HiddenFor(model => model.SolutionOutput)
            <div class="form-group">
                @Html.LabelFor(model => model.Grade, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Grade, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Grade, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        }
    }

    </div>

RipCore/RipCore/Views/Solution/Submissions.cshtml
@model RipCore.Models.ViewModels.SubmissionsOverViewModel
@for (int i = 0; i < Model.MilestoneNames.Count; i++)
{
    <h2>@Model.MilestoneNames[i].Title</h2>
    <table>
        <thead>
            <tr>
                <th>
                    @Resources.Resources.User
                </th>
                <th>
                    @Resources.Resources.Submission
                </th>
                <th>
                    @Resources.Resources.Status
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model.usersSubmissions[i])
            {
                <tr>
                    <td>
                        <h6>
                            @item.UsersName
                        </h6>
                    </td>
                    <td>
                        <h6>
                            @Html.ActionLink(@Resources.Resources.SeeSubmissions, "SubmissionDetails", new { id = item.ID, isTeacher = false })
                        </h6>
                    </td>
                    <td>
                        <h6>
                            //TODO isAccepted
                        </h6>
                    </td>
                </tr>

            }

            @foreach (var item in Model.otherSubmissions[i])
            {
                <tr>
                    <td>
                        <h6>
                            @item.UsersID
                        </h6>
                    </td>
                    <td>
                        <h6>
                            @Resources.Resources.Submission
                        </h6>
                    </td>
                    <td>
                        <h6>
                            //TODO isAccepted
                        </h6>
                    </td>
                </tr>

            }
        </tbody>
    </table>
}

RipCore/RipCore/Views/Solution/TestResults.cshtml
@model RipCore.Models.ViewModels.SubmissionViewModel

@if (Model.SolutionOutput[0] != "" && Model.ExpectedOutput[0] != "")
{
    <p>Your result: @Model.SolutionOutput</p>
    <p>Expected result: @Model.ExpectedOutput</p>
}

<section>
    <div id="editor">
        @Model.Code
    </div>
</section>
<script type="text/javascript">
    var editor = ace.edit("editor");
    //editor.setTheme("ace/theme/twilight");
   // editor.getSession().setMode("ace/mode/c#");
</script>